const products = [
  {
    id: 1,
    title: 'Super Bomb Lips',
    price: {
      currencyUnit: {
        code: 'GBP',
        numericCode: 826,
        decimalPlaces: 2,
        numeric3Code: '826',
        countryCodes: ['GG', 'IM', 'GB', 'JE'],
        pseudoCurrency: false,
        symbol: '£',
      },
      amount: 23.87,
      amountMajor: 23,
      amountMajorLong: 23,
      amountMajorInt: 23,
      amountMinor: 2387,
      amountMinorLong: 2387,
      amountMinorInt: 2387,
      minorPart: 87,
      positiveOrZero: true,
      negativeOrZero: false,
      positive: true,
      scale: 2,
      zero: false,
      negative: false,
    },
    productCategory: 'Lips',
    image:
      'https://cdn.shopify.com/s/files/1/0341/3458/9485/products/FB30008_FB5001_model_alt5.jpg?v=1656701883',
    shortDescription:
      'Our #1 gloss—now with pure, creamy color and incredible shine. Lips are instantly smoother and more voluminous-looking.',
    longDescription: 'This is the long one',
    rating: 4.5,
    rate_count: 150,
    ingredients: [],
    colors: [],
  },
  {
    id: 2,
    title: 'Super Bomb Mascara',
    price: {
      currencyUnit: {
        code: 'GBP',
        numericCode: 826,
        decimalPlaces: 2,
        numeric3Code: '826',
        countryCodes: ['GG', 'IM', 'GB', 'JE'],
        pseudoCurrency: false,
        symbol: '£',
      },
      amount: 23.87,
      amountMajor: 23,
      amountMajorLong: 23,
      amountMajorInt: 23,
      amountMinor: 2387,
      amountMinorLong: 2387,
      amountMinorInt: 2387,
      minorPart: 87,
      positiveOrZero: true,
      negativeOrZero: false,
      positive: true,
      scale: 2,
      zero: false,
      negative: false,
    },
    productCategory: 'Eyes',
    image:
      'https://cdn.shopify.com/s/files/1/0341/3458/9485/products/FB30008_FB5001_model_alt5.jpg?v=1656701883',
    shortDescription:
      'Our #1 gloss—now with pure, creamy color and incredible shine. Lips are instantly smoother and more voluminous-looking.',
    longDescription: 'This is the long one',
    rating: 4.5,
    rate_count: 150,
    ingredients: [],
    colors: [],
  },
  {
    id: 3,
    title: 'Super Bomb Eyeshadow',
    price: {
      currencyUnit: {
        code: 'GBP',
        numericCode: 826,
        decimalPlaces: 2,
        numeric3Code: '826',
        countryCodes: ['GG', 'IM', 'GB', 'JE'],
        pseudoCurrency: false,
        symbol: '£',
      },
      amount: 19.99,
      amountMajor: 23,
      amountMajorLong: 23,
      amountMajorInt: 23,
      amountMinor: 2387,
      amountMinorLong: 2387,
      amountMinorInt: 2387,
      minorPart: 87,
      positiveOrZero: true,
      negativeOrZero: false,
      positive: true,
      scale: 2,
      zero: false,
      negative: false,
    },
    productCategory: 'Lips',
    image:
      'https://cdn.shopify.com/s/files/1/0341/3458/9485/products/FB30008_FB5001_model_alt5.jpg?v=1656701883',
    shortDescription:
      'Our #1 gloss—now with pure, creamy color and incredible shine. Lips are instantly smoother and more voluminous-looking.',
    longDescription: 'This is the long one',
    rating: 4.5,
    rate_count: 150,
    ingredients: [],
    colors: [],
  },
];

export default products;
